### ISSUE TITLE
Possible Project Process Proposal

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#10]
This is more a proposal than anything else, feedback is welcome.

Two things I would like to see this project take on to improve code quality (where the 1st is arguably more important than the 2nd):

1. Tests<sup>[\[1\]][1] [\[2\]][2] [\[3\]][8]</sup>
2. A consistent style (that doesn't include 2 space indents)

There are a number of ways to achieve this and there would be a bunch of new moving parts, so I'll offer my thoughts on some of the possible parts.

**Building from the command line**

The first step is to get to a place where we can compile and upload the sketches without the Arduino IDE and, ultimately, from the command line. After looking at a few different options, I think [PlatformIO][9] looks the most promising. I'd recommend referencing the [PlatformIO Core][15] or [PlatformIO IDE][16] docs directly rather than my instructions, as they'll contain more detail, but it looks like the process for Core looks something like so (using Python's package manager `pip`):

- `pip install platformio`
- `platformio init --boards uno FolderName`
- `platformio run`

(Again, the [PlatformIO Core][15] or [PlatformIO IDE][16] docs walk through the process of installing Python, `pip`, and whatnot for Core or using Atom as an IDE.)

And we end up with a directory structure like so by default:

```
.
├── lib
│   └── README.txt
├── platformio.ini
└── src
    └── foo.cpp
```

Though, we'd probably want to have a directory structure something like so (to facilitate multiple "subprojects"):

```
.
├── CPPLINT.cfg
├── lib
│   └── README.txt
├── platformio.ini
└── src
    ├── PropulsionMiodule
    │   └── main.cpp
    └── WirelessModule
        └── main.cpp
```

(This setup would be similar to [LowPowerLab/RFM69][13], for example.)

It also looks like PlatformIO offers a way to manage and automatically download the dependencies for our programs: [Library Manager][17].

**Style Guide**

I propose this project follow [Google's C++ Style Guide][5] (for lack of our own style guide and [linter][6]). Speaking of [linters][6]...we can use [cpplint][7] to check our source files. Assuming `pip` is installed, we can use it to install cpplint and to run it against the project. For example:

- `pip install cpplint`
- `cpplint --recursive .`

We can also add a `CPPLINT.cfg` configuration file the project to adjust the settings, starting out with the following contents and adding filters as we want:

```ini
filter=-legal/copyright
exclude_files=.venv/*
```

It's a lot easier to start from Google's Style Guide and adjust than write our own.

**Tests**

First we'd need to be able to compile the project from the command line, as per above. Once we can do so, the idea of tests, or testing, can range from just verifying the project compiles successfully to having unit tests that check particular functionality in isolation.<sup>[\[1\]][1] [\[2\]][2] [\[3\]][8]</sup> I'll settle for the first here, for the sake of simplicity, but am more than welcome to help get us to the latter.

To verify that the project compiles successfully from the command-line, we'd run `platformio run` and `cpplint --recursive .` on Travis CI....

**Travis CI**

(The use of "build" in this section is loose and encompasses anything that we outline as the process for checking the source code of the project, verifying it (in whatever way), and/or compiling it.)

Travis CI has been enabled for this project for some time and has been ignoring changes without a `.travis.yml` file:

![Build only if `.travis.yml` is present][3]

Once we add a `.travis.yml` file to the repository's root, Travis will build the project (and we'll be able to see the output at [travis-ci.org/LakeMaps/microcontrollers][4]). An example of what this looks like can be found by taking a look at [a build of Hangashore][10], [the boat][11], or [the pi build script][12]. Having Travis CI build the project allows us to ensure that a particular change (or pull request) passes some checks before we continue with it. Speaking of Pull Requests....

**Pull Requests**

All of the above is a setup conducive to using GitHub's [Pull Requests][14]. We can start branching off when making changes and creating pull requests for each logical chunk of changes. This will allow us to review things before we continue with them.

  [1]:https://en.wikipedia.org/wiki/Test_automation
  [2]:https://en.wikipedia.org/wiki/Unit_testing
  [3]:https://cloud.githubusercontent.com/assets/1623628/22409531/81a23342-e665-11e6-90f6-cf75d433390a.png
  [4]:https://travis-ci.org/LakeMaps/microcontrollers
  [5]:https://google.github.io/styleguide/cppguide.html
  [6]:https://stackoverflow.com/a/30339671/1267663
  [7]:https://github.com/cpplint/cpplint
  [8]:https://stackoverflow.com/a/652309/1267663
  [9]:http://docs.platformio.org/en/latest/what-is-platformio.html
  [10]:https://travis-ci.org/LakeMaps/hangashore/builds/196198963
  [11]:https://travis-ci.org/LakeMaps/boat/builds/192873831
  [12]:https://travis-ci.org/LakeMaps/pi/builds/196248970
  [13]:https://github.com/LowPowerLab/RFM69
  [14]:https://guides.github.com/introduction/flow/
  [15]:http://docs.platformio.org/en/latest/core.html
  [16]:http://docs.platformio.org/en/latest/ide/atom.html
  [17]:http://docs.platformio.org/en/latest/librarymanager/index.html

**Comment by whymarrh** [comment]
What do we think about this? I suspect that the content above isn't completely coherent, so ask away!

**Comment by whymarrh** [comment]
As for a timeline, I don't think this is a change that would need to be implemented ASAP, but more a thing we would do before we make any more changes to the project. That said, I'm open to feedback about the timeline as well as the content above.

**Comment by FifoIronton** [comment]
I am going to be starting an Arduino project soon (once I actually get around to buying the parts) for a look into a water-column measurement tool, I'll try to follow these guidelines and get back to you when something does not make sense.

**Comment by arandell93** [comment]
I'm open to this and I think from a microcontroller perspective it would be best to implement this before we proceed with adding any other modules. We have a bit of a lull in requirements for new microcontrollers currently so it's a good time to revise and get some quality management on the go.

We can discuss moving this forward following completion of Rev 1.1 / [Rev 1.2](https://github.com/orgs/LakeMaps/projects/3), as these are simultaneous and will be a logical point for improvement within the system before adding significant hardware/software for automation.

**Comment by CalvinGregory** [comment]
If we intend to make this project long term then consistent test methods will be invaluable in the future. I feel that rev 1 is already hacked together so much that we won't see the benefit. Establishing these protocols for rev 2 is a good idea if you guys think there is time to do it. My uneducated opinion on the matter is to establish these protocols as soon as is convenient before rev 2 and once established all future code must conform but don't bother going back through all the rev 1 code to update to the new standard.

**Comment by whymarrh** [comment]
@arandell93 can bother you to take another look at this proposal? In particular, I think updating the sketches to adhere to a style guide might help with their readability and our ability to debug them.

**Comment by arandell93** [comment]
Platform IO stuff is all done. Converting projects now. Will sync to github shortly.

In terms of style, is that something that is checked by [Clang](http://docs.platformio.org/en/latest/ide/atom.html#clang-for-intelligent-code-autocompletion) or some other plugin or is it manual?

**Comment by whymarrh** [comment]
> Will sync to github shortly.

Can we get a branch on the go with that before we merge that into `master`.

> In terms of style, is that something that is checked by Clang or some other plugin or is it manual?

The one I proposed was manual but I'm open to alternatives.

**Comment by arandell93** [comment]
> Can we get a branch on the go with that before we merge that into master.

Done.

Keep getting the same error on Wireless and Propulsion .cpp builds:

collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\uno\firmware.elf] Error 1

**Comment by arandell93** [comment]
Also it keeps telling me to install Clang but I already did, and reloaded the IDE, and I can see that it's an installed package.
![image](https://cloud.githubusercontent.com/assets/10678515/22850497/b98a1e40-efe4-11e6-9aef-6d155ebd5cb9.png)
![image](https://cloud.githubusercontent.com/assets/10678515/22850500/cb0286bc-efe4-11e6-8f2f-e8d98e3318a5.png)

**Comment by whymarrh** [comment]
>     collect2.exe: error: ld returned 1 exit status
>     *** [.pioenvs\uno\firmware.elf] Error 1

That's something I'd need debug in person—there's no rush, we can work through this on Tuesday.

**Comment by arandell93** [comment]
> we can work through this on Tuesday

Anything else I should install between now and then? I'll commit my branch and sync otherwise.

**Comment by whymarrh** [comment]
I'd say just have a read through the docs and work through what you can.

**Comment by arandell93** [comment]
I did it 🎉
