### ISSUE TITLE
Instability of the wireless module receive command

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#14]
The Wireless Communication Microcontroller API's Wireless Receive command (`0x03`) has recently been quite unstable. This is a tracking issue for all the things related to diagnosing the issue and the fixes.

Related issues:

- [x] Incorrect execution of the wireless module with initial skipped bytes (#12)
- [x] Fix command check in wireless module code (#13)

(Edit this post to add new related issues as they're discovered.)

**Comment by arandell93** [comment]
Fixed command check per [54aefe1](https://github.com/LakeMaps/microcontrollers/commit/54aefe18474715917e09832b168b234d9950398b)

**Comment by whymarrh** [comment]
@arandell93 have you made any new discoveries?

**Comment by arandell93** [comment]
Nope. We need to find some repeatability in the errors we are seeing in order to properly troubleshoot.
We can go at it with a serial terminal manually tomorrow and try from both ends to see what's up.

**Comment by arandell93** [comment]
Based on our findings last night, it looks as though having the module interrupt pin (g0) mistakenly wired to Pin 1 (serial TX) on the arduino (on both modules) was causing the instability we were seeing.

Further investigation is required, but preliminary tests conducted last night (involving sending continuously and receiving using a Serial Terminal and laptop) indicated that messages are no longer having trouble being received across the link.

For reference, here are the relevant parts of the breakout board documentation from Adafruit related to wiring the module:
![image](https://cloud.githubusercontent.com/assets/10678515/23210738/8009c32a-f8d9-11e6-9e8e-85e4dcfaef37.png)

> G0 (IRQ) connects to an interrupt-capable pin. We'll be using Digital 2 but you can later change this pin too. However, it must connect a hardware Interrupt pin. Not all pins can do this! Check the board documentation for which pins are hardware interrupts, you'll also need the hardware interrupt number. For example, on UNO digital 2 is interrupt #0
