### ISSUE TITLE
Resolve incorrect 'Wireless Data Valid' flag in Receive Response

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/microcontrollers#17]
Sample response messages for reference:

```
AA 03 00 0D 00 00 00 00 15 BD B7 57 BF 55 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 59 DA
 
AA 03 00 0D 00 00 00 00 15 C1 4A 18 3E 65 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF B9 6C D7 

AA 03 00 0D 00 00 00 00 15 4A 08 1B 3F 90 91 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 59 DA     
```

Whenever a [receive command](https://github.com/LakeMaps/microcontrollers/wiki/Wireless-Communication-Microcontroller-API#command-0x03--wireless-receive) is issued requesting data from the wireless module, the third byte in the response is reserved as an indicator flag for whether or not there is valid information present in the wireless payload. This is done using the bool `rxDone`. `rxDone` is set in the following way:

```
// check if something was received (could be an interrupt from the radio)
  rxDone = radio.receiveDone();
  if (rxDone) {
    memcpy(RXPayload, (void*)radio.DATA, 61);
  }
```
In order for the data to be read from the `radio.DATA` buffer (which we know it is doing because there is different data in each response message), `rxDone` has to be true, so it must be true that `rxDone` is correctly set during this instant. It does not appear to be reset to zero at any point following this, so I am unsure where the issue is coming from.

`rxDone` is written to the `response` array in the `void Receive()` function as follows:

```
  //Prepare the response message
  response[0] = newMessage;
  response[1] = RECEIVE_CMD;
  response[2] = rxDone; //true if a message is available
```

**Comment by arandell93** [comment]
The `receiveDone()` function from the [RFM69 Library](https://github.com/LowPowerLab/RFM69/blob/master/RFM69.cpp#L370) is used as follows;

```
// checks if a packet was received and/or puts transceiver in receive (ie RX or listen) mode
bool RFM69::receiveDone() {
//ATOMIC_BLOCK(ATOMIC_FORCEON)
//{
  noInterrupts(); // re-enabled in unselect() via setMode() or via receiveBegin()
  if (_mode == RF69_MODE_RX && PAYLOADLEN > 0)
  {
    setMode(RF69_MODE_STANDBY); // enables interrupts
    return true;
  }
  else if (_mode == RF69_MODE_RX) // already in RX no payload yet
  {
    interrupts(); // explicitly re-enable interrupts
    return false;
  }
  receiveBegin();
  return false;
//}
}
```

**Comment by whymarrh** [comment]
Yeah, this is weird indeed.

I mean, the only way this would work is if the data you are assigning to `response[2]` is not the data that you mean for it to be, but that would have to be a narrowing conversion issue.... Which would mean that your boolean type is more than two byt—wait a second....

*\*searches Arduino documentation\**

Nah, it looks like booleans are 1 byte. From [Arduino Boolean Variables](https://www.arduino.cc/en/Reference/BooleanVariables):

> A **boolean** holds one of two values, true or false. (Each boolean variable occupies one byte of memory.)

And the example they use make sens—

>     boolean running = false;

Well well well....
