### ISSUE TITLE
Fix lint errors in sketches

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#18]
Follow-up to #10 (from the Style Guide section).

The project needs to be updated to fix all of the style errors in each of the sketches. I've gone ahead and added a `CPPLINT.cfg` file to each sketch in af1883b, which means that you can run [cpplint](https://github.com/cpplint/cpplint) in each of those directories to get a list of errors that need fixing.

I would recommend having a read through the full [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) before diving in.

Spoilers: there are 405 total errors, some of which are "trivial" fixes (e.g. whitespace) and some of which will require a bit more thought (e.g. [the use of integer types](https://google.github.io/styleguide/cppguide.html#Integer_Types)).

**Comment by whymarrh** [comment]
@arandell93 I'll let you figure out how you want to interact with the linter, but from the command line the process would look something like so:

```
15:22:49 (virtualenv: .virtualenv) microcontrollers (master=) $ pip install cpplint
Collecting cpplint
Installing collected packages: cpplint
Successfully installed cpplint-1.3.0
15:22:54 (virtualenv: .virtualenv) microcontrollers (master=) $ cpplint --recursive .
Arduino/Propulsion_LagTest/src/PropulsionModuleLagTest.cpp:2:  At least two spaces is best between code and comments  [whitespace/comments] [2]
Arduino/Propulsion_LagTest/src/PropulsionModuleLagTest.cpp:2:  Should have a space between // and comment  [whitespace/comments] [4]
Arduino/Propulsion_LagTest/src/PropulsionModuleLagTest.cpp:3:  Should have a space between // and comment  [whitespace/comments] [4]
Arduino/Propulsion_LagTest/src/PropulsionModuleLagTest.cpp:15:  Lines should be <= 80 characters long  [whitespace/line_length] [2]
Arduino/Propulsion_LagTest/src/PropulsionModuleLagTest.cpp:16:  At least two spaces is best between code and comments  [whitespace/comments] [2]
Arduino/Propulsion_LagTest/src/PropulsionModuleLagTest.cpp:16:  Should have a space between // and comment  [whitespace/comments] [4]
// => A lot more lines like this
```

**Comment by arandell93** [comment]
```
PS C:\Users\Anthony\Documents\GitHub\microcontrollers\Arduino\Wireless_Boat> cpplint --recursive Wireless_Boat.cpp
Skipping input 'Wireless_Boat.cpp': Can't open for reading
```
Any ideas? It opened the Propulsion module fine.

**Comment by arandell93** [comment]
Nevermind, I forgot to specify `\src\` directory.

**Comment by whymarrh** [comment]
I think you meant `.\src\`. That said, you can use `.` (a single period) to specify the current directory.

**Comment by arandell93** [comment]
`PS C:\Users\Anthony\Documents\GitHub\microcontrollers\Arduino\Wireless_Shore> cpplint --recursive src\ Wireless_Shore.cpp`

That works just fine.

**Comment by arandell93** [comment]
Issue: Since lib/ directory has been removed, the linter now sees all the libraries again. The only way to exclude them is to specify each individual library directory in the config file, which is tedious and prone to errors when adding libraries.

**Comment by whymarrh** [comment]
It "works." Using `cpplint --recursive src\ Wireless_Shore.cpp` specifies three arguments to the cpplint program:

1. `--recursive`
2. `src\`
3. `Wireless_Shore.cpp`

The recursive option is what allows you to pass directories to the program, which it then searches recursively for source files. Passing `src\` is fine. Passing `Wireless_Shore.cpp` is not needed because it's not a file in the current working directory and where it's under `src\` it will already be found by recursively looking through `src\`.

I would imagine that the first line output is:

> `Skipping input 'Wireless_Shore.cpp': Can't open for reading`

**Comment by whymarrh** [comment]
To solve the issue with cpplint checking library dependencies, you will want to update the CPPLINT.cfg (the cpplint configuration file) in each of the sketches (added in af1883b). Something like so:

```diff
diff --git a/Arduino/Wireless_Shore/CPPLINT.cfg b/Arduino/Wireless_Shore/CPPLINT.cfg
index e95c6bf..285ab2d 100644
--- a/Arduino/Wireless_Shore/CPPLINT.cfg
+++ b/Arduino/Wireless_Shore/CPPLINT.cfg
@@ -1,2 +1,2 @@
 filter=-legal/copyright
-exclude_files=lib/*
+exclude_files=.piolibdeps/*
```

**Comment by whymarrh** [comment]
@arandell93 what's the status of this?

**Comment by whymarrh** [comment]
If you're unable to sync your master branch, sync your changes on a different branch please.

**Comment by arandell93** [comment]
Just got my master to sync. AS mentioned there are a couple of errors left that require more structural changes to the code that I have been unable to resolve as it is beyond my abilities currently.

Can you take a look and see what the solutions may be?

**Comment by whymarrh** [comment]
I'll take a look and see what's left.
