### ISSUE TITLE
Remove libraries from repository

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#19]
PlatformIO offers a library manager ([PlatformIO Library Manager](http://docs.platformio.org/en/latest/librarymanager/index.html)) that can manage the installation and update of the libraries needed for a particular project/sketch. We should use this and remove the libraries from the repository.

**Comment by whymarrh** [comment]
@arandell93 [the propulsion lag test sketch still has its libraries vendored](https://github.com/LakeMaps/microcontrollers/tree/edd47ff064be5edc3b0cf4fb694452caf95d2925/Arduino/Propulsion_LagTest/lib)

**Comment by whymarrh** [comment]
[Same goes for the other propulsion sketch](https://github.com/LakeMaps/microcontrollers/tree/edd47ff064be5edc3b0cf4fb694452caf95d2925/Arduino/Propulsion_Test/lib)

**Comment by arandell93** [comment]
Oh yeah that's because I don't currently have those files in my IDE because we haven't been using them.
I'll fix that up.

**Comment by whymarrh** [comment]
Cool, 018e1f8 looks good.
