### ISSUE TITLE
Determine Range vs Bitrate Wireless Characteristics

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/microcontrollers#21]
The [RFM69HCW](https://cdn.sparkfun.com/datasheets/Wireless/General/RFM69HCW-V1.1.pdf) transmits messages using a transmit power of 100 mW (+20 dBm). The receiver sensitivity (the minimum received power level at which the receiver can discern valid signals from noise) is variable depending on the bit rate and is very broadly characterized in the datasheet:

Bit Rate|Sensitivity (dB)
|---|---|
1200|-118
4800|-114
38400|-105

Note: This is using high sensitivity mode ([page 74](https://cdn.sparkfun.com/datasheets/Wireless/General/RFM69HCW-V1.1.pdf)) which is disabled by default. It can be enabled by setting register 0x58 to 0x2D. )This is likely exposed by the [Low Power Lab](https://github.com/LowPowerLab/RFM69) library, but needs to be confirmed.

We need to do some experiments under controlled conditions to determine the maximum range of the wireless link with various bit rates in order to optimize our link latency.

**Comment by whymarrh** [comment]
Anecdotes from the library README:<sup>[\[1\]][1]</sup>

> - I have tested open-air range on these transceivers in various combinations.
> - I am happy to say that a range of upwards of 350m can be achieved with the default settings provided in the library. Some users reported upwards of 500m by lowering the bitrate, and a forum user reported 1.5miles at 1.2Kbps: see [this forum post](http://lowpowerlab.com/forum/index.php/topic,112.msg288.html) and [this blog page](http://lowpowerlab.com/moteino/#antennas)

  [1]:https://github.com/LowPowerLab/RFM69/blob/f8192e1fd3c2effdaba97e57522b408336a144c5/README.md

**Comment by whymarrh** [comment]
I'm closing this where we've removed the wireless link from the system.
