### ISSUE TITLE
Dynamic Wireless Packet Length

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/microcontrollers#22]
Refs #20 

One of the most time-consuming portions of the control system is the act of sending information over the wireless link due to the lower speeds currently used (refs #21) with the RFM69HCW.

It is desired as a method by which control latency can be reduced that we are able to define our own packet size based on the requirements of each message rather than being constrained to being exactly 61 (or 255 using non-encrypted/non-addressed packets) bytes.

This issue is to facilitate discussion and determine the suitability and impacts of such a change and to weigh its benefits and drawbacks.

**Comment by whymarrh** [comment]
> One of the most time-consuming portions of the control system is the act of sending information over the wireless link due to the lower speeds currently used (refs #21) with the RFM69HCW.

Uhhh

![Citation needed](https://imgs.xkcd.com/comics/wikipedian_protester.png)

**Comment by whymarrh** [comment]
Where we're already using the smallest packet size, what leads you to believe that sending more bytes would be any faster? How are latency and transfer size related?

**Comment by arandell93** [comment]
> Uhhh [citation needed]

#7 

> Where we're already using the smallest packet size, what leads you to believe that sending more bytes would be any faster?

Perhaps I was unclear in my OP. By _dynamic_ I mean if we only need to send 10 bytes, we just send 10 bytes with no padding to fit a fixed packet length. This would be a smaller packet than 61 bytes that we send now. The point I made about the 255 byte packet was referring to using the mode which allows us to set our own arbitrary size as long as it does not exceed 255 bytes.

> How are latency and transfer size related?

#7

**Comment by whymarrh** [comment]
My point is simply that we need to go about attaching real values to our claims before we can improve

**Comment by whymarrh** [comment]
> > Uhhh [citation needed]
>
> #7

*[Ahem](https://github.com/LakeMaps/boat/issues/47#issuecomment-293429572)*

**Comment by whymarrh** [comment]
I've mostly closed this due to the fact that sending 61 bytes has proven not to be prohibitively slow and I don't think developing the ability to send fewer bytes in order to reduce RTT will be useful at this stage. If we go the route of being able to configure variable bitrates we might want the ability to send smaller payloads but that's a discussion better had when that need arises as how we use the wireless link may very well change with in a world with variable bitrates.
