### ISSUE TITLE
Undesired Behavior from Wireless Module Start-up with Valid Data

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/microcontrollers#28]
Since the wireless module (the microcontroller) is a separate entity from the wireless radio (RFM69HCW), it is possible that there could be a valid payload in the buffer of the radio. In this case, the wireless module's first receive command would obtain valid data and thus indeterminate action can occur upon startup of the wireless module.

**Comment by whymarrh** [comment]
I'll need to think about this a bit

**Comment by whymarrh** [comment]
I'm closing this where we've removed the wireless link from the system.
