### ISSUE TITLE
Add commands to set motor speeds individually

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#32]
From the [PololuQik Library Reference](https://github.com/pololu/qik-arduino#library-reference):

> - `void setM0Speed(int speed)` <br> Sets speed and direction for motor M0. `speed` should be between -127 and 127 in 7-bit mode or -255 and 255 in 8-bit mode.  Positive values correspond to motor current flowing from the + pin to the - pin. Negative values correspond to motor current flowing from the - pin to the + pin.
> - `void setM1Speed(int speed)` <br> Sets speed and direction for motor M1.
> - `void setSpeeds(int m0Speed, int m1Speed)` <br> Sets speed and direction for both motors.

Would it make sense to add commands (e.g. `0x16` and `0x17`) to allow setting motors individually?

**Comment by whymarrh** [comment]
In writing up LakeMaps/boat#88 I noticed that the change is mostly predicated on the need for both motor speed to be set at the same time—would a better solution be to allow otherwise?

**Comment by arandell93** [comment]
> Would it make sense to add commands to allow setting motors individually?

We could do it but there isn't much purpose to just setting one. On the boat, we will not ever use just one motor as it has no real-world equivalent for vessels of this type*.

*Occasionally, sailing catamarans will use just one motor when motor-sailing as a way to decrease fuel consumption. However, motor-sailing also uses the sails so it is a different method of propulsion for which we have no equivalent.

**Comment by whymarrh** [comment]
Fair enough
