### ISSUE TITLE
Resolve intermittent Wireless Module transmission acknowledgement

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/microcontrollers#4]
The acknowledgement of a message transmission over the wireless system is still intermittent.

Per the [described protocol](https://github.com/LakeMaps/microcontrollers/wiki/Wireless-Communication-Microcontroller-API#command-0x04--wireless-transmit), the third byte in the response to a transmit request should be whether or not the acknowledgement was received.

Currently, Hangashore does not care if the ack was received or not. However, in future revisions this will be used to determine whether or not a resend of a message is required.

**Comment by arandell93** [comment]
@whymarrh is this even still an issue? I thought we were still experiencing intermittent acknowledgements when Shoreside transmits to the Pi, but I can't recall.

**Comment by whymarrh** [comment]
I don't think it is. We can close this issue and then reopen it if needed.

**Comment by arandell93** [comment]
Closed unless it is determined this is still an issue.
