### ISSUE TITLE
Investigate Latency Introduced by Propulsion Module

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/microcontrollers#6]
In an effort to reduce the overall control latency (per LakeMaps/boat#17), the time required between sending a speed command to the propulsion module and the propulsion module replying with its confirmation that a speed has been set needs to be quantified.

This can be accomplished through the use of the [`millis()`](https://cdn.arduino.cc/reference/en/language/functions/time/millis/) or [`micros()`](https://cdn.arduino.cc/reference/en/language/functions/time/micros/) command on the arduino.

**Comment by arandell93** [comment]
@whymarrh is this an appropriate use of a 'branch' of the Propulsion Module software?

**Comment by whymarrh** [comment]
Sure, if you have changes you want to commit to the project that are in a "in progress" state, branches are a good approach.

See also: [Understanding the GitHub Flow](https://guides.github.com/introduction/flow/)

**Comment by arandell93** [comment]
Latency introduced in setting motor speed is not noticeable.
"Start" occurs when microcontroller reads command from Pi.
'End" occurs after microcontroller has replied to Pi following new speed set.

![image](https://cloud.githubusercontent.com/assets/10678515/21912919/ace830f2-d903-11e6-8351-3dec1d55683a.png)
