### ISSUE TITLE
Investigate Latency Introduced by Wireless Link

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#7]
refs #6 and LakeMaps/boat#17

Have we quantified the latency introduced by the wireless link?

**Comment by arandell93** [comment]
> Have we quantified the latency introduced by the wireless link?

We have not. I can prep some test code to load onto the microcontroller to test an arbitrary round trip but the quantities measured will have little bearing on what we actually have in our system, as the overhead in the code will add as much or more latency than the actual wireless link. It is still a valid exercise though, if for no other reason that understanding qualitatively if our wireless link is fast or slow in relation to our round trip time.

**Comment by whymarrh** [comment]
I was under the impression that #6 was an effort to determine the cause of control latency. We may have a minimum latency introduced by the wireless link and quantifying the latency here would identify whether or not it is significant. Thoughts?

**Comment by arandell93** [comment]
In theory that is absolutely correct. However, what I meant is that because any test code I run is not structurally the same as the code we run on our system, there is a sort of quantum-entanglement situation where the act of adding code to facilitate measuring changes the result in a way which we cannot quantify.

So we can determine _a_ latency introduced by the wireless link, but not _the_ latency in our system.

Useful in a way, but you have to understand the limitations of the measurement being taken.

**Comment by arandell93** [comment]
Here are the theoretical rates of _communication only_ on the path of the wireless link, in one direction. This is not representative of the actual times incurred for our system, but it will give us an idea of where to look for potential improvements, as communications are nearly always the bottleneck in systems design.

Link|Speed
|:---:|:---:|
PC - Arduino|115 kbit/s UART
Shoreside Arduino - RFM69HCW|400 kbit/s SPI
RFM69HCW - RFM69HCW|4.8 kbit/s (Wireless, 900 MHz carrier)
RFM69HCW - Boat Arduino|400 kbit/s SPI
Boat Arduino - Boat RasPi|115kbit/s UART

The delays introduced by the communication are as follows:

Link|Size|Time
|:---:|:---:|:---:|
PC - Arduino (TX Command)|65 bytes|4513 us
Shoreside Arduino - RFM69HCW|61 bytes|1220 us
RFM69HCW - RFM69HCW|61 bytes|101667 us
RFM69HCW - Boat Arduino|61 bytes|1220 us
Boat Arduino - Boat RasPi (RX Command)|68 bytes|4730 us

This indicates that the wireless link's default data rate is by far the slowest link in the system. We do have the option to change the data rate to a variety of options which can be configured within the microcontroller code:
![image](https://cloud.githubusercontent.com/assets/10678515/22273977/58766f14-e27e-11e6-9e79-e71c3d2951d5.png)

**Comment by arandell93** [comment]
Closed as we have decided not to optimize the wireless link time for remote control; it is sufficient for our purposes at the moment. If we need lower latency in the future we will reevaluate.

**Comment by whymarrh** [comment]
The numbers herein are incorrect given the defaults of the RFM69 library—[see LakeMaps/boat#47](https://github.com/LakeMaps/boat/issues/47#issuecomment-293429572)
