### ISSUE TITLE
Expand descriptions in the API documentation

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/microcontrollers#8]
Currently the descriptions in the API docs for the various microcontrollers don't describe what each byte/set of bytes _mean_.

[Command 0x03 – Wireless Receive](https://github.com/LakeMaps/microcontrollers/wiki/Wireless-Communication-Microcontroller-API#command-0x03--wireless-receive), for example:

> **Request Message:**
> *  Payload Size: 1 byte (null)
>
> **Response Message:**
> *  Payload Size: 64 bytes
>
> Byte|	Description|	Valid Range
> |:---:|:---:|:---:|
> 0|Message Available|True/False
> 1 to 61|Message Received|Any
> 62 to 63|RSSI|0 to -114 (dBm)

What does "Message Available" mean? (Also, is that valid range `1` and `0`?)

(Also, what is a "null" byte?)

**Comment by arandell93** [comment]
> What does "Message Available" mean? (Also, is that valid range 1 and 0?)

This means whether or not the microcontroller has received a message to pass along to you. Valid values are 0 and 1.

> Also, what is a "null" byte?

A byte which contains no information (0x00). I added this in so that we can send some sort of payload to the microcontroller when sending a RX request in the future without messing up the size of the messages.

**Comment by whymarrh** [comment]
Maybe we can split the current description column into two columns (e.g. "title" and "description")?

**Comment by whymarrh** [comment]
> A byte which contains no information (0x00). I added this in so that we can send some sort of payload to the microcontroller when sending a RX request in the future without messing up the size of the messages.

We could probably just say `0x00` for the payload instead of "null". If I understand correctly, even if you put something in there it wouldn't mean anything, so might as well always use `0x00`?

**Comment by arandell93** [comment]
>Maybe we can split the current description column into two columns (e.g. "title" and "description")?

I am okay with this but I will do it later haha. Leave this issue open until I fix it.

> We could probably just say 0x00 for the payload instead of "null". If I understand correctly, even if you put something in there it wouldn't mean anything, so might as well always use 0x00?

Yep! I clarified on the wiki.

**Comment by arandell93** [comment]
> Maybe we can split the current description column into two columns (e.g. "title" and "description")?

Done and closing.

**Comment by whymarrh** [comment]
If I may request a few more updates, the following commands don't have tables for their requests:

1. [`0x00`](https://github.com/LakeMaps/microcontrollers/wiki/Wireless-Communication-Microcontroller-API#command-0x00--reset-wireless-module)
2. [`0x03`](https://github.com/LakeMaps/microcontrollers/wiki/Wireless-Communication-Microcontroller-API#command-0x03--wireless-receive)
2. [`0x10`](https://github.com/LakeMaps/microcontrollers/wiki/Propulsion-Microcontroller-API#command-0x10--reset-motor-controller)
3. [`0x13`](https://github.com/LakeMaps/microcontrollers/wiki/Propulsion-Microcontroller-API#command-0x13--set-motor-speeds)
4. [`0x14`](https://github.com/LakeMaps/microcontrollers/wiki/Propulsion-Microcontroller-API#command-0x14---get-motor-currents)
5. [`0x15`](https://github.com/LakeMaps/microcontrollers/wiki/Propulsion-Microcontroller-API#command-0x15--get-errors)

Where the bytes are supposed to be "null", it might make sense to have something like:

Byte|	Description|	Valid Range
|:---:|:---:|:---:|
0|Null Byte (just use `0x00`)|Anything

**Comment by arandell93** [comment]
Done & Closing.
